# Generated by Django 5.2.1 on 2025-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=50)),
                ('experiencia', models.PositiveIntegerField()),
                ('turno', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=15)),
            ],
        ),
    ]
