# Generated by Django 5.2.1 on 2025-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('edad_aplicacion', models.PositiveIntegerField()),
                ('vigencia', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
